FROM ghcr.io/actions/actions-runner:latest

USER root

# Install required base packages
RUN apt-get update && \
    apt-get install -y apt-utils apt-transport-https ca-certificates curl gnupg jq lsb-release software-properties-common wget make gh unzip time

# Install powershell 7
RUN export VERSION_ID=$(grep VERSION_ID /etc/os-release | cut -d'=' -f2 | tr -d '"') && \
    wget -q https://packages.microsoft.com/config/ubuntu/$VERSION_ID/packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && \
    apt-get update && \
    apt-get install -y powershell

# Install the Az module
RUN pwsh -command Install-Module -Name Az -Repository PSGallery -Force -Scope AllUsers

# Install azure cli
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

# Install AWS CLI
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    tar -xzf awscliv2.zip && \
    ./aws/install && \
    rm -rf awscliv2.zip aws

# Install kubeconform
RUN curl -L https://github.com/yannh/kubeconform/releases/download/v0.6.7/kubeconform-linux-amd64.tar.gz \
    -o kubeconform.tar.gz && \
    tar -xzf kubeconform.tar.gz && \
    chmod +x kubeconform

# Clean up
RUN rm packages-microsoft-prod.deb && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# COPY entrypoint.sh ./entrypoint.sh
COPY github-actions-runner/entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

USER runner

ENTRYPOINT ["./entrypoint.sh"]
